backend:
  name: git-gateway
  branch: master
media_folder: "src/site/img"
public_folder: "/img"
media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: inspro
    api_key: 923619112787378
slug:
  encoding: "ascii"
  clean_accents: true
collections:
  - name: "strony"
    label: "Strony"
    files:
      - label: "Landing Page"
        name: "home"
        file: "src/site/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "home" }
          - label: "Kogo zapraszamy"
            name: "kogo_zapraszamy"
            fields:
              - { label: "Nagłówek", name: "naglowek", widget: "string" }
              - { label: "Treść", name: "tresc", widget: "markdown" }
          - label: "Co dajemy?"
            name: "co_dajemy"
            fields:
              - { label: "Nagłówek", name: "naglowek", widget: "string" }
              - { label: "Treść", name: "tresc", widget: "markdown" }
          - label: "Zgłoś się na szkolenie"
            name: "zglos_sie_na_szkolenie"
            fields:
              - { label: "Link do formularza", name: "link_do_formularza", widget: "string" }
          - label: "Czego oczekujemy?"
            name: "czego_oczekujemy"
            fields:
              - { label: "Nagłówek", name: "naglowek", widget: "string" }
              - { label: "Treść", name: "tresc", widget: "markdown" }
          - label: "O projekcie"
            name: "o_projekcie"
            fields:
              - { label: "Nagłówek", name: "naglowek", widget: "string" }
              - { label: "Treść", name: "tresc", widget: "markdown" }
          - label: "Dokumenty do pobrania"
            name: "dokumenty"
            fields:
              - { label: "Nagłówek", name: "naglowek", widget: "string" }
              - { label: "Treść", name: "tresc", widget: "markdown" }
      - label: "Poznaj nas"
        name: "poznaj"
        file: "src/site/poznaj-nas.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "poznaj-nas" }
          - label: "Organizacje"
            name: "organizacje"
            widget: "list"
            fields:
              - { label: "Nazwa", name: "nazwa", widget: "string" }
              - { label: "Logo", name: "logo", widget: "string" }
              - { label: "Opis", name: "opis", widget: "markdown" }
  - name: "dzieje"
    label: "Dzieje się"
    folder: "src/site/dzieje-sie"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Zajawka", name: "zajawka", widget: "markdown" }
      - { label: "Treść", name: "body", widget: "markdown" }
  - name: "polecamy"
    label: "Polecamy"
    folder: "src/site/polecamy"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Zajawka", name: "zajawka", widget: "markdown" }
      - { label: "Treść", name: "body", widget: "markdown" }